# Generated by Django 4.1.7 on 2023-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_room_user_id2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_id2',
            field=models.IntegerField(),
        ),
    ]
